#!/usr/bin/env python3
"""
make_hyphen_fixture.py — hard-wrap a real text and break words across lines.

    python tools/make_hyphen_fixture.py

Writes `tests/fixtures/hyphenated.txt` and `tests/keys/hyphenated.hyphens`.

**Synthetic damage applied to real prose**, which is the important difference
from the earlier generators. The vocabulary, spelling and compound habits are
Charlotte Brontë's; only the line breaks are invented. A rule that relies on the
document's own vocabulary has to be tested against a real one, because the
whole question is whether real vocabulary supplies enough evidence.

Ground truth is exact: the generator knows what word it broke.

Three cases are produced deliberately:

1. **Ordinary words** broken mid-word. The hyphen must go.
2. **Real hyphenated compounds** broken at their own hyphen — `to-morrow`,
   `drawing-room`. The hyphen must stay. *Jane Eyre* has 1,146 of these, and
   joining them blindly yields `tomorrow` and `drawingroom`.
3. **Dashes at line ends**, preceded by a space. These are punctuation, not
   hyphenation, and must not be touched at all.

Deterministic: a fixed seed, so the fixture and its key never drift.
"""

from __future__ import annotations

import random
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tests" / "fixtures" / "CBronte_Jane.txt"
OUT = ROOT / "tests" / "fixtures" / "hyphenated.txt"
KEY = ROOT / "tests" / "keys" / "hyphenated.hyphens"

SEED = 1847
WIDTH = 64
PARAGRAPHS = 260
MIN_FRAGMENT = 2      # never leave a one-letter stub


def main() -> int:
    if not SRC.exists():
        print(f"source not found: {SRC}")
        return 1

    rng = random.Random(SEED)
    paras = [p for p in SRC.read_text(encoding="utf-8").split("\n")
             if p.strip()][:PARAGRAPHS]

    lines: list[str] = []
    truth: list[tuple[int, str]] = []   # (1-based line of the hyphen, word)

    for para in paras:
        words = para.split()
        cur = ""
        for w in words:
            if not cur:
                cur = w
                continue
            if len(cur) + 1 + len(w) <= WIDTH:
                cur += " " + w
                continue

            # The word does not fit. Break it if it is long enough to be worth
            # breaking, otherwise start a new line.
            core = w.strip(".,;:!?\"'()")
            room = WIDTH - len(cur) - 1
            if (len(core) >= 6 and room > MIN_FRAGMENT + 1
                    and core.isalpha() or "-" in core):
                cut = None
                if "-" in core and 1 < core.index("-") < len(core) - 2:
                    # A real compound: break at its own hyphen, so the hyphen
                    # in the output is genuine and must survive.
                    cut = core.index("-") + 1
                elif core.isalpha() and len(core) >= 6:
                    lo, hi = MIN_FRAGMENT, len(core) - MIN_FRAGMENT
                    if hi > lo:
                        cut = min(max(room - 1, lo), hi)
                if cut and MIN_FRAGMENT <= cut <= len(core) - MIN_FRAGMENT:
                    left, right = core[:cut], core[cut:]
                    if left.endswith("-"):
                        lines.append(cur + " " + left)
                    else:
                        lines.append(cur + " " + left + "-")
                    truth.append((len(lines), core))
                    trail = w[len(core) + w.index(core):]
                    cur = right + trail
                    continue
            lines.append(cur)
            cur = w
        if cur:
            lines.append(cur)
        lines.append("")

    # Case 3: dashes at line ends. Punctuation, not hyphenation.
    dashes = 0
    for i, ln in enumerate(lines):
        if ln and not ln.endswith("-") and rng.random() < 0.02:
            lines[i] = ln + " -"
            dashes += 1

    text = "\n".join(lines).rstrip("\n") + "\n"
    OUT.write_text(text, encoding="utf-8")

    compounds = [(n, w) for n, w in truth if "-" in w]
    plain = [(n, w) for n, w in truth if "-" not in w]

    KEY.write_text(f"""# De-hyphenation key: hyphenated.txt
#
# NOT a region key. Region keys use the .key extension and measure.py parses
# every one it finds; a per-line key must use its own suffix, as .furniture
# and .catchwords do.
#
# Generated by tools/make_hyphen_fixture.py with seed {SEED}.
# Source prose: CBronte_Jane.txt. Only the line breaks are invented.
#
# One row per broken word: LINE<TAB>EXPECTED
# LINE is the 1-based line carrying the trailing hyphen.
#
# {len(truth)} broken words: {len(plain)} ordinary, {len(compounds)} real
# hyphenated compounds whose hyphen must SURVIVE the join.
#
# {dashes} lines end in a space-dash. Those are punctuation and must not be
# touched at all; they are not listed here.

""" + "".join(f"{n}\t{w}\n" for n, w in truth), encoding="utf-8")

    print(f"wrote {OUT.relative_to(ROOT)}  ({len(lines):,} lines)")
    print(f"wrote {KEY.relative_to(ROOT)}")
    print(f"  {len(plain)} ordinary words broken")
    print(f"  {len(compounds)} compounds broken at their own hyphen")
    print(f"  {dashes} trailing dashes that must be left alone")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
